# Generated by Django 3.2.7 on 2022-11-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=6)),
                ('description', models.TextField()),
                ('age', models.IntegerField(default=0)),
                ('image', models.TextField()),
            ],
        ),
    ]
